language: c

notifications:
  email: false

services:
  - docker

before install:
  - docker pull galoisinc/besspin:besspin_light

script:
  - docker run -v ${TRAVIS_BUILD_DIR}:/FreeRTOS-mirror galoisinc/besspin:besspin_light /bin/bash -c "cd FreeRTOS-mirror; ./compile_all.sh"
