language: c

notifications:
  email: false

services:
  - docker

before install:
  - docker pull galoisinc/besspin:besspin_light

script:
  - docker run galoisinc/besspin:besspin_light -v ${TRAVIS_BUILD_DIR}:/FreeRTOS-mirror -c /bin/bash "cd FreeRTOS-mirror; ./compile_all.sh"
